#theme: jekyll-theme-prologue
remote_theme: StowarzyszenieSamopal/jekyll-theme-prologue
title: Samopał
description:
subtitle: Tanie sianie na śniadanie !
###description: >- # this means to ignore newlines until "baseurl:"
###  This is the demo site for a Jekyll theme version of
###  HTML5 UP's sleek, responsive site template Prologue.
author: Samopał
email: kontakt@samopal.pl
avatar: assets/images/avatar.png

# You'll want to customize url and baseurl for your own site:
###baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social icons settings:
telegram_url: https://t.me/StowarzyszenieSamopal
joutube_url: https://www.youtube.com/channel/UCsv7C8jWdDmfJfafaTEkuDg
twitter_url:
facebook_url: https://fb.me/StowarzyszenieSamopal
googleplus_url:
instagram_url: https://www.instagram.com/stowarzyszeniesamopal
linkedin_url:
github_url:
stackoverflow_url:
pinterest_url: https://pl.pinterest.com/sssamopal
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:
encoding: UTF-8
collections: [sections]

